version: "3"

networks:
  mcserver:

services:
  loki:
    image: grafana/loki:2.4.1
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - mcserver

  promtail:
    image: grafana/promtail:2.4.1
    volumes:
      - ./promtail/log:/var/log
    command: -config.file=/etc/promtail/config.yml
    networks:
      - mcserver