version: "3.9"

services:
  mc-server:
    container_name: mc_server
    restart: always
    image: kevinserver:latest
    environment:
      - MCRAM=12G
      - RAM=13G
    volumes:
      - ./minecraft:/srv/minecraft
    networks:
      - mcserver
    ports:
      - 25565:25565
      - 25575:25575
      - 60606:60606/udp
      - 8100:8100
  mcserver_loki:
    container_name: mcserver_loki
    image: grafana/loki
    restart: always
    command: -config.file=/etc/loki/loki.yaml
    volumes:
      - ./loki/loki.yaml:/etc/loki/loki.yaml
    ports:
      - "3100:3100"
    networks:
      - mcserver
  mcserver_exporter:
    container_name: mcserver_exporter
    restart: always
    image: ghcr.io/dirien/minecraft-exporter:latest
    entrypoint: /usr/bin/minecraft-exporter  --web.listen-address=":8000"  --mc.world="/minecraft/world"  --mc.rcon-address="mc-server:25575"  --mc.rcon-password="kevinmatt"  --mc.mod-server-stats=fabric  --mc.name-source="offline"
    volumes:
      - ./minecraft/world:/minecraft/world
    networks:
      - mcserver
  mcserver_grafana:
    container_name: mcserver_grafana
    restart: always
    image: grafana/grafana-enterprise
    volumes:
      - ./grafana-storage:/var/lib/grafana
    ports:
      - 3002:3000
    networks:
      - mcserver
  mcserver_prometheus:
    container_name: mcserver_prometheus
    restart: always
    image: prom/prometheus
    volumes:
      - ./prometheus:/etc/prometheus
    networks:
      - mcserver
  node-exporter:
    #inside Port is 9100
    container_name: node-exporter
    restart: always
    image: prom/node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    networks:
      - mcserver

networks:
  mcserver:
