global:
  scrape_interval:     2s
  evaluation_interval: 2s

scrape_configs:
  # self monitor
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']
        labels:
          instance: prometheus

  # node metrics collector
  - job_name: main_server
    static_configs:
      - targets: ['node-exporter:9100']
        labels:
          instance: localhost

  # UnifiedMetrics collector (https://github.com/Cubxity/UnifiedMetrics)
  - job_name: UnifiedMetrics
    static_configs:
      - targets: ['mc_server:9100']
        labels:
          instance: localhost
          minecraft: "true"

  # https://github.com/dirien/minecraft-prometheus-exporter
  - job_name: dirien-minecraft-exporter
    static_configs:
      - targets: ['dirien-minecraft-exporter:8000']
        labels:
          instance: localhost
          minecraft: "true"