global:
  scrape_interval:     2s
  evaluation_interval: 2s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']
        labels:
          instance: prometheus

  - job_name: mincraft
    static_configs:
      - targets: ['mcserver_exporter:8000']
        labels:
          instance: localhost

  - job_name: main_server
    static_configs:
      - targets: ['node-exporter:9100']
        labels:
          instance: localhost